QRGenProject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("qrgen.urls")),
    path("qrcode/", include("handlescan.urls")),
    path("", include("django_prometheus.urls")),
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "home.views.not_found"

accounts/urls.py
from django.urls import path
from .views import Register, Login, logoutuser
app_name = "accounts"


urlpatterns = [
    path('register/', Register, name="register-page"),
    path('login/', Login, name="login-page"),
    path('logout/', logoutuser, name="logout" )
]

home/urls.py
from django.urls import path
from .views import home_page, about_page, learn_page, contact_page, documentation

app_name = 'home'

urlpatterns = [
    path('', home_page, name='home-page'),
    path('about-us/', about_page, name='about-page'),
    path('learn/', learn_page, name='learn-page'),
    path('contact-us/', contact_page, name='contact-page'),
    path('documentation/',documentation, name='documentation-page')
]

qrgen/urls.py
from django.urls import path
from .views import GenerationDashboardView, MainDashboardView, DeleteQrCode, EditQrCode, download
from . import views
app_name = 'qrgen'

urlpatterns = [
    path('generate/', GenerationDashboardView.as_view(), name='generate'),
    path('', MainDashboardView.as_view(), name='dashboard'),
    path('delete/<int:code_id>/', DeleteQrCode.as_view(), name='delete_qrcode'),
    path('edit/<int:code_id>/', EditQrCode.as_view(), name='edit_qrcode'),
    path('download/<int:code_id>/<str:type>/', download, name='download_qrcode'),    
]

qrgen/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary_storage.storage import RawMediaCloudinaryStorage
from django.core.files.storage import default_storage

from QRGenProject.settings import DEBUG
from django_prometheus.models import ExportModelOperationsMixin

# Create your models here.

ACTION_TYPE = (
    ("web", "Website URL"),
    ("tex", "Text"),
    ("pdf", "PDF"),
    ("biz", "Business Card"),
    ("wap", "Whatsapp"),
    ("img", "Image"),
    ("eml", "Email"),
    ("eve", "Events"),
)


if DEBUG:
    storage = default_storage
else:
    storage = RawMediaCloudinaryStorage()


class File(ExportModelOperationsMixin("file"), models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    file = models.FileField(upload_to="user_files/", storage=storage)

    def __str__(self):
        return self.name


class QrType(ExportModelOperationsMixin("qrtype"), models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class QrCode(ExportModelOperationsMixin("qrcode"), models.Model):
    title = models.CharField(max_length=50, null=True, default="Untitled")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    type = models.ForeignKey(QrType, on_delete=models.CASCADE)
    is_dynamic = models.BooleanField(default=True, blank=True)
    img = models.ImageField(upload_to="qrcodes/")
    input_url = models.URLField(max_length=255, blank=True, null=True)
    action_url = models.URLField(max_length=255, blank=True, null=True)
    action_type = models.CharField(max_length=3, choices=ACTION_TYPE)
    scan_count = models.IntegerField(default=None, null=True, blank=True)
    date_gen = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    file = models.ForeignKey(File, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.title} ({self.date_gen})"


# request.build_absolute_uri(f"/download/{file.id}")

qrgen/views.py
from django.shortcuts import render
from django.views import View
import qrcode
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

# for manipulating our models
from .models import QrCode, QrType, File

# for the ajax request
from django.http import JsonResponse
from django.core import serializers

# for manipulating folders
from QRGenProject.settings import BASE_DIR
import os

# for qrcode image manipulations
from PIL import Image
import urllib.request, urllib.parse, urllib.error


def create_or_get_types():
    if (len(QrType.objects.all())) == 0:
        code_types = ["dynamic", "static"]

        for code_type in code_types:
            QrType.objects.create(name=code_type)

    return QrType.objects.all()


# @login_required(login_url='/admin/login/')
# this should be the default user login (i.e. /accounts/login/)
# note: this is for FBV, for CBV, we use LoginRequiredMixin


class GenerationDashboardView(LoginRequiredMixin, View):
    login_url = "/accounts/login/"

    def get(self, request):
        QrTypes = create_or_get_types()

        context = {
            "code_types": QrTypes,
        }

        return render(request, "qrgen/generation.html", context)

    def post(self, request):
        # if request.is_ajax

        if "generate" in request.POST:
            # collecting form data (url...qrcode_type, action_type)

            form_data = request.POST

            # get qr_type (from database)

            type = QrType.objects.get(name=request.POST["qrcode_type"])

            # partially create a qrcode object

            QrCode.objects.create(
                user=request.user,
                type=type,
                action_type=form_data["action_type"],
            )

            uploads = ["pdf", "img", "biz"]

            # add the qrcode object's action url

            # - get the last added qrcode object
            this_qrcode = QrCode.objects.all().last()

            if this_qrcode.action_type not in uploads:
                # it is a url not a file uploaded
                this_qrcode.input_url = form_data["url"]
                this_qrcode.action_url = form_data["url"]

            else:
                # it is either a pdf or image upload
                # create a File object
                File.objects.create(
                    user=request.user,
                    name=request.FILES["upload_file"].name,
                    file=request.FILES["upload_file"],
                )

                # get the created file
                created_file = File.objects.all().last()

                # add the created file to the QrCode object
                this_qrcode.file = created_file

                # update the action url to download the file
                this_qrcode.action_url = request.build_absolute_uri(
                    f"/qrcode/download/{created_file.id}"
                )

            if this_qrcode.type.name == "dynamic":
                # - this is the url that the qrcode should point to either ways
                # --- (be it upload or url, so long as it is dynamic)
                # ---- if it is an upload... it will be redirected to the download function
                # ---- else it will be redirected to the input url
                this_qrcode.action_url = request.build_absolute_uri(
                    f"/qrcode/dynamic/{this_qrcode.id}"
                )

            else:
                # qrcode is static type
                this_qrcode.is_dynamic = False

            # save all these modifications to the qrcode object
            this_qrcode.save()

            # having saved the QrCode object, (and a File object (if it was and uploaded file)),
            # we now generate a qrcode image with the QrCode's action_url
            # create a temporary folder to store all the qrcode images if it doesn't exist

            folder_path = BASE_DIR / "temp/qrcodes/"
            if not os.path.exists(folder_path):
                os.makedirs(folder_path)

            # print(folder_path)
            qr_img = qrcode.make(this_qrcode.action_url)

            # folder for the qrcode being created

            qr_folder_path = BASE_DIR / f"temp/qrcodes/{this_qrcode.id}/"

            if not os.path.exists(qr_folder_path):
                os.makedirs(qr_folder_path)
            img_path = f"temp/qrcodes/{this_qrcode.id}/qrcode-{this_qrcode.id}.png"
            qr_img.save(img_path)

            # add and save the qr_img to the QrCode object
            image = open(img_path, "r+b")
            this_qrcode.img.save(f"qrcode-{this_qrcode.id}.png", image, save=True)
            image.close()
            # print(this_qrcode)
            # serialize the new qrcode object
            # ser_qrcode = serializers.serialize('json', [this_qrcode, ])
            # send to client site

            return JsonResponse({"qrcode_img": this_qrcode.img.url}, status=200)
        else:
            return JsonResponse({"error": ""}, status=400)


class MainDashboardView(LoginRequiredMixin, View):
    login_url = "/accounts/login"

    def get(self, request):
        user_codes = (
            QrCode.objects.all().filter(user_id=request.user.id).order_by("-date_gen")
        )
        download_options = {1: "png", 2: "jpeg", 3: "pdf"}
        active_codes = user_codes.filter(is_active=True)

        context = {
            "qrcodes": user_codes,
            "code_count": user_codes.count(),
            "active_codes": active_codes,
            "active_count": active_codes.count(),
            "download_options": download_options,
            "upload_types": ["pdf", "img", "biz"],
        }
        return render(request, "qrgen/dashboard.html", context)

    def post(request):
        return HttpResponseRedirect(reverse("qrgen:dashboard"))


class EditQrCode(LoginRequiredMixin, View):
    login_url = "/accounts/login"

    def get(self, request):
        return HttpResponseRedirect(reverse("qrgen:dashboard"))

    def post(self, request, code_id):
        qrcode = QrCode.objects.get(id=code_id)
        if "change_content" in request.POST:
            if "new_content" in request.POST:
                new_url = request.POST["new_content"]
                qrcode.input_url = new_url
            elif (
                "new_file" in request.FILES
            ):  # Vérifier si le champ de fichier new_file existe
                old_file = qrcode.file
                File.objects.create(
                    user=request.user,
                    name=request.FILES["new_file"].name,
                    file=request.FILES["new_file"],
                )
                created_file = File.objects.all().last()
                qrcode.file = created_file
                if old_file is not None:
                    old_file.delete()

        elif "change_title" in request.POST:
            new_title = request.POST["new_title"]
            qrcode.title = new_title

        qrcode.save()

        return HttpResponseRedirect(reverse("qrgen:dashboard"))


class DeleteQrCode(LoginRequiredMixin, View):
    login_url = "/accounts/login"

    def get(self, request, code_id):
        qrcode = QrCode.objects.get(id=code_id)
        qrcode.delete()
        return HttpResponseRedirect(reverse("qrgen:dashboard"))

    def post(self, request, code_id):
        return HttpResponseRedirect(reverse("qrgen:dashboard"))


def download(request, code_id, type):
    # the the qrcode object
    qrcode = QrCode.objects.get(id=code_id)

    # check for the qrcode locally
    file_path = f"temp/qrcodes/{code_id}/{qrcode.title}.png"

    if not os.path.exists(file_path):
        # getting the image from the cloud and save in a temp folder
        img = urllib.request.urlopen(qrcode.img.url).read()
        temp = BASE_DIR / "temp"
        qrcode_folder = f"{temp}/qrcodes/{code_id}"

        if not os.path.exists(temp):
            os.makedirs(temp)

        if not os.path.exists(qrcode_folder):
            os.makedirs(qrcode_folder)

            # save the image as png
        file_path = BASE_DIR / f"temp/qrcodes/{code_id}/{qrcode.title}.png"
        fhand = open(file_path, "wb")
        fhand.write(img)
        fhand.close()

    # converting it if type = pdf or jpeg (because it is already in png)
    if type != "png":
        png_img = Image.open(file_path)
        new_img = png_img.convert("RGB")
        if type == "pdf":
            file_path = BASE_DIR / f"temp/qrcodes/{code_id}/{qrcode.title}.pdf"
            new_img.save(file_path, format="pdf")
        else:
            file_path = BASE_DIR / f"temp/qrcodes/{code_id}/{qrcode.title}.jpg"
            new_img.save(BASE_DIR / f"temp/qrcodes/{code_id}/{qrcode.title}.jpg")

    # downloading it to the user's device
    with open(file_path, "rb") as fh:
        response = HttpResponse(fh.read(), content_type="application/adminupload")
        response["Content-Disposition"] = "inline;filename=" + os.path.basename(
            file_path
        )
        return response

qrgen/templates/qrgen/dashboard.html
{% load static %}

<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>QrGen59 | Dashboard</title>
  <link rel="stylesheet" href="{% static 'css/dashboard.css' %}" />
  <link rel="shortcut icon" href="{% static 'favicon.png' %}" type="image/x-icon">
  <script defer src="{% static 'js/dashbrd.js' %} "></script>
</head>

<body>
  <header class="header">
    <nav class="navbar">
      <div class="logo">
        <a href="{% url 'home:home-page' %}">QrGen<span>59</span></a>
      </div>
      <div class="profile_btns">
        <div class="profile_icon">
          <h1>{{request.user.username|slice:':1'}}</h1>
        </div>
        <div class="profile_links">
          <a href="{% url 'home:home-page' %}">Home</a>
          <a href="{% url 'accounts:logout' %}">Log out</a>
        </div>
      </div>

      </div>
    </nav>
  </header>
  <main class="wrapper">
    <div class="side_bar">
      <div class="search_form_div">
        <form action="">
          <input type="text" class="search" onkeypress="search()" placeholder="search" />
          <button class="search_btn" onclick="search()">
            <img src="{% static 'img/image/icon/search-normal.png' %}" alt="" />
          </button>
        </form>
      </div>
      <!-- <div class="navigator_header">
        <h6>QR Codes</h6>
      </div>
      <div class="page_navigator">
        <div class="navigator_options active" id="all">
          <img src="{% static 'img/image/icon/all-icon.png' %}" alt="" />
          <button onclick="windows.location.reload()">All ({{code_count}})</button>

        </div> -->
      <div class="navigator_header">
        <h6>QR Codes</h6>
      </div>
      <div class="page_navigator">
        <div class="navigator_options active" id="all">
          <img src="{% static 'img/image/icon/all-icon.png' %}" alt="" />
          <button>All ({{code_count}})</button>
        </div>
        <div class="navigator_options" id="active">
          <img src="{% static 'img/image/icon/active-icon.png' %}" alt="" />
          <button>Active ({{active_count}})</button>
        </div>
      </div>
      <div class="logout_btn">
        <a href="{% url 'accounts:logout' %}"><button>
            <img src="{% static 'img/image/icon/log-out-icon.png' %}" alt="" />
            <p>Log out</p>
          </button>
        </a>
      </div>
    </div>
    <div class="main_content">
      <div class="main_content_header">
        <div class="filter_btn">
          <button>
            <img src="{% static 'img/image/icon/all-icon.png' %}" alt="" />
            <p>All QR codes</p>
          </button>
        </div>
        <div class="create_qr_navigator_btn">
          <a href="{% url 'qrgen:generate' %}">
            <button>Create QR code</button>
          </a>
        </div>
      </div>
      <div class="saved_data_wrapper">
        {% if qrcodes %} {% for qrcode in qrcodes %}
        <div class="saved_data">
          <div class="delete_modal">
            <div class="alert_icon">
              <img src="{% static 'image/icon/alert.png' %}" alt="" />
            </div>
            <div class="delete_msg_section">
              <h3>Are you sure?</h3>
              <p>
                Do you really want to delete this record?. This process cannot
                be undone
              </p>
            </div>
            <div class="button_section">
              <a class="cancelx">
                <button>Cancel</button>
              </a>
              <a class="delete" href="{% url 'qrgen:delete_qrcode' qrcode.id %}">
                <button>Delete</button>
              </a>
            </div>
          </div>
          <section class="qr_image">
            <div class="title">
              <h5>
                {{qrcode.title}}
                <span>
                  <img class="edit_icon" src="{% static 'img/image/icon/edit-2.png' %}" alt="" />
                </span>
              </h5>
            </div>
            <img src="{{qrcode.img.url}}" alt="" class="code" />
            <form class="title_form" action="{% url 'qrgen:edit_qrcode' qrcode.id %}" method="POST">
              {% csrf_token %}
              <h5>Enter new title</h5>
              <div>
                <input name="new_title" type="text" />
                <input class="change_btn" type="submit" name="change_title" value="Change" />
              </div>
              <img class="modal_cancel_icon" src="{% static 'img/image/icon/basic-cancel-icon.png' %}" alt="" />
            </form>
          </section>
          <div class="des_share_del">
            <form class="edit_form" action="{% url 'qrgen:edit_qrcode' qrcode.id %}" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <h5>Enter new Qrcode content</h5>
              <div>
                {% if qrcode.action_type in upload_types %}
                <input type="file" name="new_file" required>
                {% else %}
                <input name="new_content" type="url" required>
                {% endif %}
                <input class="change_btn_x" type="submit" name="change_content" value="Change" />
              </div>
              <img class="content_modal_cancel" src="{% static 'img/image/icon/basic-cancel-icon.png' %}" alt="" />
            </form>
            <div class="qr_des">
              {% if qrcode.is_dynamic %}
              <div class="scan">
                <h5>Scan ({{ qrcode.scan_count }})</h5>
              </div>
              {% endif %}
              <div class="date">
                <img src="{% static 'img/image/icon/clock-icon.png' %}" alt="" />
                <p>{{ qrcode.date_gen }}</p>
              </div>
              <div class="link">
                <img src="{% static 'img/image/icon/link-icon.png' %}" alt="" />
                <p>{{qrcode.type}}</p>
              </div>
                {% if qrcode.action_type in upload_types %}
                <div class="link">
                  <img src="{% static 'img/image/icon/file-icon.png' %}" alt="" />
                <p>{{qrcode.file}}</p>
              </div>
                {% endif %}
              {% if qrcode.is_dynamic %}
              <button class="content_edit_btn">Edit</button>
              {% endif %}
            </div>
            <div class="qr_share_del">
              <div class="qr_download">
                <button class="download_btn">Download</button>
                <div class="download_options">
                  {% for id, option in download_options.items %}
                  <a href="{% url 'qrgen:download_qrcode' qrcode.id option %}"><button class="download_btn"
                      id="btn_{{option}}">
                      <img src="{% static 'image/icon/download-button-icon.png' %}" alt="" />
                      <p>Download {{option}}</p>
                    </button></a>

                  {% endfor %}
                  <img class="cancel" src="{% static 'img/image/icon/basic-cancel-icon.png' %}" alt="" />
                </div>
              </div>
              <div class="share_del">
                <button class="share">
                  <img src="{% static 'img/image/icon/send-icon.png' %}" alt="" />
                  <p>Share</p>
                </button>
                <button class="delete_icon">
                  <img src="{% static 'image/icon/delete-icon.png' %}" alt="" />
                  <p>Delete</p>
                </button>
                <div class="share-notification">
                  <h1>feature may not work on some devices</h1>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %} {% else %}
        <div class="main_content_blank">
          <div class="data_blank">
            <section class="qr_image">
              <img src="{% static 'image/qr-code-blur.png' %}" alt="" />
            </section>
            <p>Generate a QR code, download, scan and share</p>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </main>
</body>

</html>