QRGenProject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("qrgen.urls")),
    path("qrcode/", include("handlescan.urls")),
    path("", include("django_prometheus.urls")),
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "home.views.not_found"

accounts/urls.py
from django.urls import path
from .views import Register, Login, logoutuser
app_name = "accounts"


urlpatterns = [
    path('register/', Register, name="register-page"),
    path('login/', Login, name="login-page"),
    path('logout/', logoutuser, name="logout" )
]

home/urls.py
from django.urls import path
from .views import home_page, about_page, learn_page, contact_page, documentation

app_name = 'home'

urlpatterns = [
    path('', home_page, name='home-page'),
    path('about-us/', about_page, name='about-page'),
    path('learn/', learn_page, name='learn-page'),
    path('contact-us/', contact_page, name='contact-page'),
    path('documentation/',documentation, name='documentation-page')
]

qrgen/urls.py
from django.urls import path
from .views import GenerationDashboardView, MainDashboardView, DeleteQrCode, EditQrCode, download
from . import views
app_name = 'qrgen'

urlpatterns = [
    path('generate/', GenerationDashboardView.as_view(), name='generate'),
    path('', MainDashboardView.as_view(), name='dashboard'),
    path('delete/<int:code_id>/', DeleteQrCode.as_view(), name='delete_qrcode'),
    path('edit/<int:code_id>/', EditQrCode.as_view(), name='edit_qrcode'),
    path('download/<int:code_id>/<str:type>/', download, name='download_qrcode'),    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static 'nav.css' %}" />
  <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet" />
  <link rel="shortcut icon" href="{% static 'favicon.png' %}" type="image/x-icon">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
  <!-- css styling -->
  {% block css %}
  {% endblock css %}
  <title>QrGen59 | {{title}}</title>
</head>

<body>
  <!-- Navbar Section -->
  <header>
    <div class="scroll-up-btn">
      <i class="fas fa-angle-up"></i>
    </div>
    <nav class="navbar">
      <div class="wrapper">
        <div class="logo">
          <a href="{% url 'home:home-page' %}">QrGen<span>59</span></a>
        </div>
        {% with request.resolver_match.url_name as url_name %}
        <ul class="nav-links">
          <li>
            <a href="{% url 'home:home-page' %}"
              class="menu-btn {% if url_name == 'home-page'%} active {% endif %}">Home</a>
          </li>
          <li>
            <a href="{% url 'home:learn-page' %}"
              class="menu-btn {% if url_name == 'learn-page'%} active {% endif %}">Learn</a>
          </li>
          <li>
            <a href="{% url 'home:contact-page' %}"
              class="menu-btn {% if url_name == 'contact-page'%} active {% endif %}">Contact Us</a>
          </li>
          <li>
            <a href="{% url 'home:about-page' %}"
              class="menu-btn {% if url_name == 'about-page'%} active {% endif %}">About Us</a>
          </li>
        </ul>
        {% endwith %}
        <div class="nav-buttons">
          {% if request.user.is_authenticated %}
          <a href="{% url 'qrgen:dashboard' %}" class="btn2 light">Dashboard</a>
          {% else %}
          <a href="{% url 'accounts:register-page' %}" class="btn1 dark">Get Started</a>
          <a href="{% url 'accounts:login-page' %}" class="btn2 light">Sign in</a>
          {% endif %}
        </div>
        <div class="menu-btn">
          <i class="fas fa-bars"></i>
        </div>
      </div>
    </nav>
  </header>
  <!-- Body-Content   -->
  {% block content %}
  {% endblock content %}
  <footer>
    <div class="footer-container">
      <div class="footer-logo">
        <a href="{% url 'home:home-page' %}">QrGen59</a>
      </div>
      {% with request.resolver_match.url_name as url_name %}
      <ul class="footer-nav1">
        <li>
          <a href="{% url 'home:learn-page' %}" class="{% if url_name == 'learn-page'%} active {% endif %}">Learn</a>
        </li>
        <li>
          <a href="{% url 'home:documentation-page' %}"
            class="{% if url_name == 'documentation-page'%} active {% endif %}">Documentation</a>
        </li>
        <li>
          <a href="{% url 'home:contact-page' %}" class="{% if url_name == 'contact-page'%} active {% endif %}">Contact
            Us</a>
        </li>
        <li>
          <a href="{% url 'home:about-page' %}" class="{% if url_name == 'about-page'%} active {% endif %}">About Us</a>
        </li>
      </ul>
      {% endwith %}
    </div>
    <div class="line"></div>
    <ul class="footer-nav2">
      <p>Copyright@2022</p>
    </ul>
  </footer>
  {% comment %} SCRIPTS {% endcomment %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="{% static 'nav.js' %}"></script>
  {% block scripts %}
  {% endblock scripts %}
</body>

</html>